### ISSUE TITLE
Pyinstaller error with pyutilib.component.core (Syntax error in core3.py) (Trac #123)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#127]
Pyinstaller gives an error with pyutilib.component.core-4.5.6. Note that this issue doesn't affect the ability to run microdrop using the python interpreter.

```
Syntax error in core3.py
('invalid syntax', ('core3.py', 320, 34, 'class Interface(object, metaclass=InterfaceMeta):\n'))
Traceback (most recent call last):
  File "C:\pyinstaller\Build.py", line 1494, in <module>
    main(args[0], configfilename=opts.configfile)
  File "C:\pyinstaller\Build.py", line 1472, in main
    build(specfile)
  File "C:\pyinstaller\Build.py", line 1429, in build
    execfile(spec)
  File "microdrop.spec", line 19, in <module>
    excludes=['opencv', 'flatland', 'pygtkhelpers',])
  File "C:\pyinstaller\Build.py", line 347, in __init__
    self.__postinit__()
  File "C:\pyinstaller\Build.py", line 298, in __postinit__
    self.assemble()
  File "C:\pyinstaller\Build.py", line 416, in assemble
    analyzer.analyze_script(script)
  File "C:\pyinstaller\mf.py", line 572, in analyze_script
    return self.analyze_r('__main__')
  File "C:\pyinstaller\mf.py", line 466, in analyze_r
    newnms = self.analyze_one(name, nm, imptyp, level)
  File "C:\pyinstaller\mf.py", line 525, in analyze_one
    mod = self.doimport(nm, ctx, fqname)
  File "C:\pyinstaller\mf.py", line 587, in doimport
    mod = parent.doimport(nm)
  File "C:\pyinstaller\mf.py", line 761, in doimport
    mod = self.subimporter.getmod(nm)
  File "C:\pyinstaller\mf.py", line 355, in getmod
    mod = owner.getmod(nm)
  File "C:\pyinstaller\mf.py", line 117, in getmod
    co = compile(string.replace(stuff, "\r\n", "\n"), py[0], 'exec')
  File "core3.py", line 320
    class Interface(object, metaclass=InterfaceMeta):
                                     ^
SyntaxError: invalid syntax
```

A workaround is to install the following versions in the order specified:

```
pip install pyutilib.component.core==4.4.1
pip install pyutilib.component.loader
```

The pyutilib.component.loader version doesn't seem to matter, but 3.3.1 definitely works.

The install_dependencies.py script should be updated to reflect this.

Migrated from http://microfluidics.utoronto.ca/microdrop/ticket/123
```json
{
    "status": "closed", 
    "changetime": "2014-04-17T19:39:01", 
    "description": "Pyinstaller gives an error with pyutilib.component.core-4.5.6. Note that this issue doesn't affect the ability to run microdrop using the python interpreter.\n\n{{{\nSyntax error in core3.py\n('invalid syntax', ('core3.py', 320, 34, 'class Interface(object, metaclass=InterfaceMeta):\\n'))\nTraceback (most recent call last):\n  File \"C:\\pyinstaller\\Build.py\", line 1494, in <module>\n    main(args[0], configfilename=opts.configfile)\n  File \"C:\\pyinstaller\\Build.py\", line 1472, in main\n    build(specfile)\n  File \"C:\\pyinstaller\\Build.py\", line 1429, in build\n    execfile(spec)\n  File \"microdrop.spec\", line 19, in <module>\n    excludes=['opencv', 'flatland', 'pygtkhelpers',])\n  File \"C:\\pyinstaller\\Build.py\", line 347, in __init__\n    self.__postinit__()\n  File \"C:\\pyinstaller\\Build.py\", line 298, in __postinit__\n    self.assemble()\n  File \"C:\\pyinstaller\\Build.py\", line 416, in assemble\n    analyzer.analyze_script(script)\n  File \"C:\\pyinstaller\\mf.py\", line 572, in analyze_script\n    return self.analyze_r('__main__')\n  File \"C:\\pyinstaller\\mf.py\", line 466, in analyze_r\n    newnms = self.analyze_one(name, nm, imptyp, level)\n  File \"C:\\pyinstaller\\mf.py\", line 525, in analyze_one\n    mod = self.doimport(nm, ctx, fqname)\n  File \"C:\\pyinstaller\\mf.py\", line 587, in doimport\n    mod = parent.doimport(nm)\n  File \"C:\\pyinstaller\\mf.py\", line 761, in doimport\n    mod = self.subimporter.getmod(nm)\n  File \"C:\\pyinstaller\\mf.py\", line 355, in getmod\n    mod = owner.getmod(nm)\n  File \"C:\\pyinstaller\\mf.py\", line 117, in getmod\n    co = compile(string.replace(stuff, \"\\r\\n\", \"\\n\"), py[0], 'exec')\n  File \"core3.py\", line 320\n    class Interface(object, metaclass=InterfaceMeta):\n                                     ^\nSyntaxError: invalid syntax\n}}}\n\nA workaround is to install the following versions in the order specified:\n\n{{{\npip install pyutilib.component.core==4.4.1\npip install pyutilib.component.loader\n}}}\n\nThe pyutilib.component.loader version doesn't seem to matter, but 3.3.1 definitely works.\n\nThe install_dependencies.py script should be updated to reflect this.", 
    "reporter": "ryan", 
    "cc": "", 
    "resolution": "wontfix", 
    "_ts": "1397763541728826", 
    "component": "microdrop", 
    "summary": "Pyinstaller error with pyutilib.component.core (Syntax error in core3.py)", 
    "priority": "major", 
    "keywords": "", 
    "version": "0.1", 
    "time": "2012-08-28T17:08:04", 
    "milestone": "Microdrop 1.0", 
    "owner": "ryan", 
    "type": "defect"
}
```

**Comment by cfobel** [comment]
Trac update at 20140314T06:08:19: 
* ryan commented:

> This is no longer necessary with the portable python installer.
> 
> See #148


* ryan changed resolution from "" to "wontfix"
* ryan changed status from "new" to "closed"

**Comment by cfobel** [comment]
Trac update at 20140417T19:39:01: ryan changed component from "" to "microdrop"
