### ISSUE TITLE
Problem installing task-scheduler (Trac #151)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#155]
I am getting the following error when running the `pip install -r requirements.txt` file. The problems seems to be intermittent (i.e., it doesn't happen every time), but I was able to reproduce it on a clean repository.

```
Obtaining task-scheduler from git+https://github.com/cfobel/task_scheduler.git@master#egg=task-scheduler-dev (from -r requirements.txt (line 17))
  Cloning https://github.com/cfobel/task_scheduler.git (to master) to c:\users\ryan\documents\dev\python\microdrop\src\task-scheduler
Unpacking objects: 100% (30/30), done.
  Running setup.py egg_info for package task-scheduler
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "C:\Users\ryan\Documents\dev\python\microdrop\src\task-scheduler\setup.py", line 7, in <module>
        version=version.getVersion(),
      File "version.py", line 116, in getVersion
        raise ValueError('Cannot find the version number')
    ValueError: Cannot find the version number
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\ryan\Documents\dev\python\microdrop\src\task-scheduler\setup.py", line 7, in <module>
    version=version.getVersion(),
  File "version.py", line 116, in getVersion
    raise ValueError('Cannot find the version number')
ValueError: Cannot find the version number

----------------------------------------
Command python setup.py egg_info failed with error code 1
```

Migrated from http://microfluidics.utoronto.ca/microdrop/ticket/151
```json
{
    "status": "closed", 
    "changetime": "2014-04-17T19:39:01", 
    "description": "I am getting the following error when running the `pip install -r requirements.txt` file. The problems seems to be intermittent (i.e., it doesn't happen every time), but I was able to reproduce it on a clean repository.\n\n{{{\nObtaining task-scheduler from git+https://github.com/cfobel/task_scheduler.git@master#egg=task-scheduler-dev (from -r requirements.txt (line 17))\n  Cloning https://github.com/cfobel/task_scheduler.git (to master) to c:\\users\\ryan\\documents\\dev\\python\\microdrop\\src\\task-scheduler\nUnpacking objects: 100% (30/30), done.\n  Running setup.py egg_info for package task-scheduler\n    Traceback (most recent call last):\n      File \"<string>\", line 14, in <module>\n      File \"C:\\Users\\ryan\\Documents\\dev\\python\\microdrop\\src\\task-scheduler\\setup.py\", line 7, in <module>\n        version=version.getVersion(),\n      File \"version.py\", line 116, in getVersion\n        raise ValueError('Cannot find the version number')\n    ValueError: Cannot find the version number\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n  File \"<string>\", line 14, in <module>\n  File \"C:\\Users\\ryan\\Documents\\dev\\python\\microdrop\\src\\task-scheduler\\setup.py\", line 7, in <module>\n    version=version.getVersion(),\n  File \"version.py\", line 116, in getVersion\n    raise ValueError('Cannot find the version number')\nValueError: Cannot find the version number\n\n----------------------------------------\nCommand python setup.py egg_info failed with error code 1\n}}}", 
    "reporter": "ryan", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1397763541728826", 
    "component": "microdrop", 
    "summary": "Problem installing task-scheduler", 
    "priority": "major", 
    "keywords": "", 
    "version": "0.1", 
    "time": "2014-03-14T02:14:25", 
    "milestone": "Microdrop 1.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by cfobel** [comment]
Trac update at 20140314T03:11:35: ryan commented:

> Adding a tag "v0.0" to the first commit of the `task-scheduler` repository allows pip to successfully finish the installation; however, the "task_scheduler" subdirectory (left over from when it was included as a git submodule) has not yet been removed from the `microdrop` repository. This package seems to take precedence over the version installed by `pip`. When I removed the "task_scheduler" subdirectory, microdrop is no longer able to start:
> 
> ```
> [INFO]: Loading config file from C:\Users\ryan\AppData\Roaming\microdrop\microdrop.ini
> [INFO]: [App] processing requested deletions.
> [INFO]: [App] processing requested renames.
> [DEBUG]: [APP UPDATE SERVER] server url: http://microfluidics.utoronto.ca/update
> [INFO]: Loading plugins:
> [DEBUG]: [App] update_log_file None
> (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'view'",), <
> traceback object at 0x04E2A4E0>) {}
>   File "C:\Python\lib\runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "C:\Python\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "C:\Users\ryan\Documents\dev\dropbot\software\microdrop\microdrop\microdrop.py", line 49, in
> <module>
>     my_app.run()
>   File "microdrop\app.py", line 341, in run
>     FormViewDialog.default_parent = self.main_window_controller.view
> ```

**Comment by cfobel** [comment]
Trac update at 20140320T13:53:56: 
* cfobel commented:

> ```
> #!md
> 
> This bug was caused by trying to eliminate the `from constraint from *` in `task_scheduler/__init__.py`.  See [here][1] for more details.
> 
> [1]: https://github.com/wheeler-microfluidics/task_scheduler/commit/b899ff8446e3e2d71300f516ee45e14c1be07441


* cfobel changed resolution from "" to "fixed"
* cfobel changed status from "new" to "closed"

**Comment by cfobel** [comment]
Trac update at 20140417T19:39:01: ryan changed component from "" to "microdrop"
