### ISSUE TITLE
missing module: plugin_manager (Trac #12)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#16]
As of version cc0f8d7, plugin_manager Python module is missing:

Traceback (most recent call last):
  File "microdrop.py", line 24, in <module>
    from gui.main_window_controller import MainWindowController
  File "/home/christian/Documents/dev/udrop/microdrop/microdrop/gui/main_window_controller.py", line 23, in <module>
    from plugin_manager import ExtensionPoint, IPlugin
ImportError: No module named plugin_manager

Migrated from http://microfluidics.utoronto.ca/ticket/12
```json
{
    "status": "closed", 
    "changetime": "2014-04-17T19:39:01", 
    "description": "As of version cc0f8d7, plugin_manager Python module is missing:\n\nTraceback (most recent call last):\n  File \"microdrop.py\", line 24, in <module>\n    from gui.main_window_controller import MainWindowController\n  File \"/home/christian/Documents/dev/udrop/microdrop/microdrop/gui/main_window_controller.py\", line 23, in <module>\n    from plugin_manager import ExtensionPoint, IPlugin\nImportError: No module named plugin_manager", 
    "reporter": "cfobel", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1397763541728826", 
    "component": "microdrop", 
    "summary": "missing module: plugin_manager", 
    "priority": "major", 
    "keywords": "", 
    "version": "0.1", 
    "time": "2011-10-08T23:46:42", 
    "milestone": "Microdrop 1.0", 
    "owner": "ryan", 
    "type": "defect"
}
```

**Comment by cfobel** [comment]
Trac update at 20111010T23:27:36: 
* cfobel commented:

> Need to install [https://software.sandia.gov/trac/pyutilib/wiki/GettingStarted/Installing !PyUtillib]
> 
> See #8


* cfobel changed resolution from "" to "fixed"
* cfobel changed status from "new" to "closed"

**Comment by cfobel** [comment]
Trac update at 20140417T19:39:01: ryan changed component from "core" to "microdrop"
