### ISSUE TITLE
Error running post-install hook when there is a space in the Windows username

### ISSUE THREAD

**Issue by ryanfobel** [wheeler-microfluidics/microdrop#196]
To reproduce this error, create a new Windows user with a space in their username (e.g., "User Name"). Then [install MicroDrop using the default options](https://github.com/wheeler-microfluidics/microdrop/wiki/Quick-Start-Guide) and try downloading and installing any of the standard plugins (e.g., the [dmf_control_board_plugin](https://github.com/wheeler-microfluidics/dmf_control_board_plugin)) using the [MicroDrop gui](https://github.com/wheeler-microfluidics/microdrop/wiki/Quick-Start-Guide#install-plugins-through-microdrop-gui). Here's the traceback:

```
2016-11-29 11:28:52 [INFO:microdrop.app]:   running post install hook for wheelerlab.dmf_control_board_plugin
2016-11-29 11:29:01 [INFO:root]: Traceback (most recent call last):
  File "C:\Users\New User\MicroDrop\lib\site-packages\microdrop\app.py", line 208, in __init__
    plugin_manager.post_install(p)
  File "C:\Users\New User\MicroDrop\lib\site-packages\microdrop\plugin_manager.py", line 98, in post_install
    try_admin=True, working_dir=hooks_path)
  File "C:\Users\New User\MicroDrop\lib\site-packages\run_exe\__init__.py", line 87, in run_exe
    output = run_func(exe, params, True)
  File "C:\Users\New User\MicroDrop\lib\site-packages\run_exe\__init__.py", line 50, in run_func
    (exe, params, os.getcwd(), return_code))
RuntimeError: Error running: on_plugin_install.bat "C:\Users\New User\MicroDrop\python.exe"
  (in C:\Users\New User\Documents\MicroDrop\plugins\dmf_control_board_plugin\hooks\Windows).
Process returned error code: 1

2016-11-29 11:29:01 [ERROR:root]: Error running post-install hook for dmf_control_board_plugin.
Traceback (most recent call last):
  File "C:\Users\New User\MicroDrop\lib\site-packages\microdrop\app.py", line 208, in __init__
    plugin_manager.post_install(p)
  File "C:\Users\New User\MicroDrop\lib\site-packages\microdrop\plugin_manager.py", line 98, in post_install
    try_admin=True, working_dir=hooks_path)
  File "C:\Users\New User\MicroDrop\lib\site-packages\run_exe\__init__.py", line 87, in run_exe
    output = run_func(exe, params, True)
  File "C:\Users\New User\MicroDrop\lib\site-packages\run_exe\__init__.py", line 50, in run_func
    (exe, params, os.getcwd(), return_code))
RuntimeError: Error running: on_plugin_install.bat "C:\Users\New User\MicroDrop\python.exe"
  (in C:\Users\New User\Documents\MicroDrop\plugins\dmf_control_board_plugin\hooks\Windows).
Process returned error code: 1
```

Note that once you've executed these steps, you can reproduce the error from the MicroDrop environment prompt through the following commands:

```
> cd C:\Users\New User\Documents\MicroDrop\plugins\dmf_control_board_plugin\hooks\Windows
> on_plugin_install.bat "C:\Users\New User\MicroDrop\python.exe"

   User\MicroDrop\python.exe""=="" was unexpected at this time.
```

The problem seems to be related to the way in which Windows batch files handles spaces in path names.

**Comment by ryanfobel** [comment]
I implemented a fix for the [dmf_control_board_plugin](https://github.com/wheeler-microfluidics/dmf_control_board_plugin/commit/a371cb960a9ebd2d9e061502a6338132eca451a4). A similar fix will have to be made for all MicroDrop plugins.

Instead of maintaining a separate `.bat` file for all plugins, we should maybe consider implementing a default `on_plugin_install` hook (that could be overridden only where necessary). That way, we could apply fixes similar to the one linked above in a single place for the vast majority of plugins.
