### ISSUE TITLE
Exe doesn't work (Trac #58)

### ISSUE THREAD

**Issue by cfobel** [wheeler-microfluidics/microdrop#62]
As of version 0.1.135, the pyinstaller compiled exe does not work when built on either Window XP or Windows 7 (although they display different symptoms and therefore may represent two different problems).

Under Windows XP, the application won't even start (displaying some kind of permission error), whereas under Windows 7, the program starts but generates the following traceback:

INFO: Root directory: D:\docs\ryan\dev\python\microdrop\dist\microdrop
INFO: Adding service ExperimentLogController to environment microdrop
INFO: Adding service ExperimentLogController to environment microdrop
D:\docs\ryan\dev\python\microdrop\build\pyi.win32\microdrop\outPYZ1.pyz/gui.experiment_log_controller:56: GtkWarning: Unable to locate theme engine in module_path: "wimp",
INFO: Adding service ConfigController to environment microdrop
INFO: Adding service ConfigController to environment microdrop
INFO: Adding service MainWindowController to environment microdrop
INFO: Adding service MainWindowController to environment microdrop
INFO: Adding service MainWindowController to environment microdrop
INFO: Adding service DmfDeviceController to environment microdrop
INFO: Adding service DmfDeviceController to environment microdrop
INFO: Adding service DmfDeviceController to environment microdrop
FROZEN!
Traceback (most recent call last):
  File "<string>", line 53, in <module>
  File "C:\pyinstaller\iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller\iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "D:\docs\ryan\dev\python\microdrop\build\pyi.win32\microdrop\outPYZ1.pyz/app", line 48, in <module>
  File "C:\pyinstaller\iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller\iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "D:\docs\ryan\dev\python\microdrop\build\pyi.win32\microdrop\outPYZ1.pyz/gui.video_controller", line 34, in <module>
  File "C:\pyinstaller\iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "C:\pyinstaller\iu.py", line 521, in doimport
    exec co in mod.__dict__
  File "D:\docs\ryan\dev\python\microdrop\build\pyi.win32\microdrop\outPYZ1.pyz/microdrop", line 35, in <module>
  File "C:\pyinstaller\iu.py", line 454, in importHook
    del sys.modules[fqname]
KeyError: 'dmf_control_board.microdrop'

Migrated from http://microfluidics.utoronto.ca/ticket/58
```json
{
    "status": "closed", 
    "changetime": "2014-04-17T19:39:01", 
    "description": "As of version 0.1.135, the pyinstaller compiled exe does not work when built on either Window XP or Windows 7 (although they display different symptoms and therefore may represent two different problems).\n\nUnder Windows XP, the application won't even start (displaying some kind of permission error), whereas under Windows 7, the program starts but generates the following traceback:\n\nINFO: Root directory: D:\\docs\\ryan\\dev\\python\\microdrop\\dist\\microdrop\nINFO: Adding service ExperimentLogController to environment microdrop\nINFO: Adding service ExperimentLogController to environment microdrop\nD:\\docs\\ryan\\dev\\python\\microdrop\\build\\pyi.win32\\microdrop\\outPYZ1.pyz/gui.experiment_log_controller:56: GtkWarning: Unable to locate theme engine in module_path: \"wimp\",\nINFO: Adding service ConfigController to environment microdrop\nINFO: Adding service ConfigController to environment microdrop\nINFO: Adding service MainWindowController to environment microdrop\nINFO: Adding service MainWindowController to environment microdrop\nINFO: Adding service MainWindowController to environment microdrop\nINFO: Adding service DmfDeviceController to environment microdrop\nINFO: Adding service DmfDeviceController to environment microdrop\nINFO: Adding service DmfDeviceController to environment microdrop\nFROZEN!\nTraceback (most recent call last):\n  File \"<string>\", line 53, in <module>\n  File \"C:\\pyinstaller\\iu.py\", line 436, in importHook\n    mod = _self_doimport(nm, ctx, fqname)\n  File \"C:\\pyinstaller\\iu.py\", line 521, in doimport\n    exec co in mod.__dict__\n  File \"D:\\docs\\ryan\\dev\\python\\microdrop\\build\\pyi.win32\\microdrop\\outPYZ1.pyz/app\", line 48, in <module>\n  File \"C:\\pyinstaller\\iu.py\", line 436, in importHook\n    mod = _self_doimport(nm, ctx, fqname)\n  File \"C:\\pyinstaller\\iu.py\", line 521, in doimport\n    exec co in mod.__dict__\n  File \"D:\\docs\\ryan\\dev\\python\\microdrop\\build\\pyi.win32\\microdrop\\outPYZ1.pyz/gui.video_controller\", line 34, in <module>\n  File \"C:\\pyinstaller\\iu.py\", line 436, in importHook\n    mod = _self_doimport(nm, ctx, fqname)\n  File \"C:\\pyinstaller\\iu.py\", line 521, in doimport\n    exec co in mod.__dict__\n  File \"D:\\docs\\ryan\\dev\\python\\microdrop\\build\\pyi.win32\\microdrop\\outPYZ1.pyz/microdrop\", line 35, in <module>\n  File \"C:\\pyinstaller\\iu.py\", line 454, in importHook\n    del sys.modules[fqname]\nKeyError: 'dmf_control_board.microdrop'", 
    "reporter": "ryan", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1397763541728826", 
    "component": "microdrop", 
    "summary": "Exe doesn't work", 
    "priority": "major", 
    "keywords": "", 
    "version": "0.1", 
    "time": "2012-02-20T04:50:54", 
    "milestone": "Microdrop 1.0", 
    "owner": "cfobel", 
    "type": "defect"
}
```

**Comment by cfobel** [comment]
Trac update at 20120224T01:38:05: 
* christian@fobel.net commented:

> commit c8a2f3bd70b3f5ad709ce1d98529152ed92178e0
> Merge: 7eb9ee2ca8812c93d18bc06b486deebd4af951c4 f5b5345b7f1a2503aee800c92df9ba6622d42eea
> Author: Christian Fobel <christian@fobel.net>
> Date:   Wed Feb 22 17:29:45 2012 -0500
> 
>     Merge branch 'fix_exe'.  Fixes #62.


* christian@fobel.net changed resolution from "" to "fixed"
* christian@fobel.net changed status from "new" to "closed"

**Comment by cfobel** [comment]
Trac update at 20120224T01:38:08: christian@fobel.net commented:

> commit b983410822ba843c03689441a14859258efbd48e
> Author: Christian Fobel <christian@fobel.net>
> Date:   Wed Feb 22 15:46:58 2012 -0500
> 
>     Fix EXE build on Windows 7. See #62.

**Comment by cfobel** [comment]
Trac update at 20140417T19:39:01: ryan changed component from "core" to "microdrop"
